name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["quickstart/models", "demo/models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  quickstart:
    +database: analytics
    marts:
      jaffle_shop:
        +schema: jaffle_shop
        materialized: view
  demo:
    +database: analytics